version: "3.8"
services:
  backgammon:
    image: backgammon
    build:
      context: .
      network: host
    container_name: backgammon
    command: ["gunicorn", "src.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:8000"]
    ports:
      - 8000:8000


